version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "maven"
    ignore: 
      - dependency-name: "jakarta.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.glassfish.*"
        update-types: ["version-update:semver-major"]  
